FROM ffeldhaus/xpra-html5-minimal

LABEL version="1.0"
LABEL maintainer="florian.feldhaus@gmail.com"

# skip interactive configuration dialogs
ENV DEBIAN_FRONTEND noninteractive

# add winswitch repository and install Xpra
RUN apt-get update --allow-insecure-repositories && \
    apt-get install wireshark -y && \
    # binutils are necessary to use strip utility
    apt-get install -y --no-install-recommends binutils && \
    # this is required due to incompatibilities on Centos 7 hosts see issue #4 for details
    ldconfig -p | grep libQt5Core.so.5 | cut -d '>' -f 2 | xargs -I{} strip --remove-section=.note.ABI-tag {} && \
    apt-get remove -y --purge binutils && \
    apt-get autoremove -y --purge && \
    rm -rf /var/lib/apt/lists/*

# allow non-root users to capture network traffic
RUN setcap 'CAP_NET_RAW+eip CAP_NET_ADMIN+eip' /usr/bin/dumpcap

# set default password to access wireshark
ENV XPRA_PASSWORD wireshark

RUN apt-get update --allow-insecure-repositories && \
    apt-get install libwireshark-dev wireshark-dev cmake git python3 python3-pip python-xdg -y

WORKDIR /opt

RUN git clone --recurse-submodules https://github.com/geontech/wireshark-vrtgen

WORKDIR /opt/wireshark-vrtgen

RUN bash -xc "pushd vrtgen && \
    pip3 install . && \
    popd"

RUN pip3 install MarkupSafe==2.0.1 pyinotify xdg python-uinput netifaces paramiko

RUN cmake -B build
WORKDIR /opt/wireshark-vrtgen/build/
RUN make install

# start wireshark by default
CMD ["wireshark --fullscreen"]
